name: CI Test

on:
  pull_request:
    branches: [main]

jobs:
  test-action:
    name: Acceptance Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:12
        env:
          MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
          MARIADB_DATABASE: wordpress
          MARIADB_USER: username
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Chrome for webdriver-based testing
        uses: browser-actions/setup-chrome@v2

      - name: Setup Chrome Driver for webdriver-based testing
        uses: nanasess/setup-chromedriver@v2

      - name: Start Chrome Driver process in background
        run: |
          mkdir -p tests/_output
          chromedriver --port=4444 > tests/_output/chromedriver.log 2>&1 &

      - name: Test
        uses: impressible-wp/wordpress-ci@v2
        with:
          plugins: .

          test-command: |

            # Running "server-side" commands in the WordPress CI container
            wpci-cmd wp plugin activate user-profile-tabs

            # Your test may access the WordPress CI's URL with this environment
            # variable
            echo "WordPress is accessible here: $WORDPRESS_CI_URL"

            # Running "client-side" commands in GitHub Actions runner
            composer install
            composer run test
    
      - name: Save Artifacts
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: test-artifacts
          path: tests/_output
